CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);
INSERT INTO public."__EFMigrationsHistory"("MigrationId", "ProductVersion") VALUES('20240313134530_Initial', '5.0.0');


CREATE TABLE public.suppliers (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description text NULL,
	cnpj int8 NOT NULL,
	CONSTRAINT "PK_suppliers" PRIMARY KEY (id)
);

CREATE TABLE public.products (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description text NULL,
	is_active bool NOT NULL,
	date_created timestamp NOT NULL,
	date_valid timestamp NOT NULL,
	fk_supplier int8 NOT NULL,
	CONSTRAINT "PK_products" PRIMARY KEY (id)
);
CREATE INDEX "IX_products_fk_supplier" ON public.products USING btree (fk_supplier);

INSERT INTO public.suppliers( description, cnpj) VALUES('string', 64722539000137);
INSERT INTO public.suppliers ( description, cnpj) VALUES( 'NIKE', 92505267000159);
INSERT INTO public.suppliers ( description, cnpj) VALUES( 'Penaulty', 55262541000180);
INSERT INTO public.suppliers( description, cnpj) VALUES( 'Supplier X', 25117928000181);
INSERT INTO public.suppliers ( description, cnpj) VALUES( 'Supplier Y', 57580014000149);


INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES( 'Tenis nike update', false, '2024-03-12 17:22:42.456', '2024-03-13 17:22:42.456', 1);
INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES( 'Tenis novo', true, '2024-03-12 13:56:55.131', '2024-03-13 13:56:55.131', 2);
INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES( 'Chuteira nike', true, '2024-03-12 13:56:55.131', '2024-03-13 13:56:55.131', 2);
INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES( 'Bola Volei marka', true, '2024-03-12 13:56:55.131', '2024-03-13 13:56:55.131', 2);
INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES( 'Bola Volei penaulty', true, '2024-03-12 13:56:55.131', '2024-03-13 13:56:55.131', 2);
INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES( 'Bola Volei nike', true, '2024-03-12 13:56:55.131', '2024-03-13 13:56:55.131', 2);
INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES('Product A', true, '2024-03-13 12:00:00.000', '2024-03-20 12:00:00.000', 4);
INSERT INTO public.products
( description, is_active, date_created, date_valid, fk_supplier)
VALUES('Product B', true, '2024-03-14 14:30:00.000', '2024-03-21 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('bola', true, '2024-03-14 14:30:00.000', '2024-03-21 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('Tenis', true, '2024-03-14 14:30:00.000', '2024-03-21 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('chuteira', true, '2024-03-14 14:30:00.000', '2024-03-21 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('caneleira', true, '2024-03-14 14:30:00.000', '2024-03-21 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('bola volei', true, '2024-03-14 14:30:00.000', '2024-03-21 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('bola futebol', true, '2024-03-14 14:30:00.000', '2024-03-21 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('camiseta', true, '2024-03-10 14:30:00.000', '2024-03-12 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('camiseta internacional', true, '2024-03-10 14:30:00.000', '2024-03-12 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('camiseta gremio', true, '2024-03-10 14:30:00.000', '2024-03-12 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('camiseta Flamengo', true, '2024-03-10 14:30:00.000', '2024-03-12 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('camiseta Coritiba', true, '2024-03-10 14:30:00.000', '2024-03-12 14:30:00.000', 5);
INSERT INTO public.products
(description, is_active, date_created, date_valid, fk_supplier)
VALUES('camiseta Palmeiras', true, '2024-03-10 14:30:00.000', '2024-03-12 14:30:00.000', 5);
